# Site settings
title: DCP Reading Editions
email: digitalcavendishproject@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Reading editions of Margaret Cavendish's texts.
baseurl: "/DCP" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: S_moores
github_username:  digicavendish

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
